services:
  
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: pasword
      DATABASE_NAME: db
    ports:
      - '80:8000'
    restart: "no"
    depends_on:
      - db  

  
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: pasword 
      MYSQL_DATABASE: db      
    ports:
      - "3306:3306"
    restart: no

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"  
    depends_on:
      - db
    restart: no

	
